name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Patch MMKV codegen (ensure in CI)
        run: node ./scripts/patch-mmkv-codegen.js

      - name: Show MMKV package.json (debug)
        run: cat node_modules/react-native-mmkv/package.json

      - name: Clean Android build folders
        run: rm -rf android/app/build android/build

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Workaround for react-native-mmkv codegen on CI
        run: mkdir -p node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/

      - name: Gradle preBuild (generate autolinking files)
        run: |
          cd android
          ./gradlew :app:preBuild
          cd ..

      - name: Copy dummy MMKV CMakeLists.txt (for CI build)
        run: node ./scripts/copy-mmkv-cmakelists.js

      - name: Patch Android-autolinking.cmake (comment out MMKV codegen and link)
        run: node ./scripts/patch-autolinking-cmake.js
      
      - name: Show Android-autolinking.cmake before Gradle build
        run: bash scripts/debug-autolinking-cmake.sh

      - name: Build Android APK with react-native-android-build-apk
        uses: wzieba/react-native-android-build@v1
        with:
          node-version: 18
          java-version: 17
          package-manager: npm
          build-variant: release
