name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Clean Android build folders
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            if (Test-Path android/app/build) { Remove-Item -Recurse -Force android/app/build }
            if (Test-Path android/build) { Remove-Item -Recurse -Force android/build }
          else
            rm -rf android/app/build android/build
          fi
        shell: pwsh

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        if: runner.os != 'Windows'
        run: chmod +x android/gradlew

      - name: Workaround for react-native-mmkv codegen on CI
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mkdir "node_modules\\react-native-mmkv\\android\\build\\generated\\source\\codegen\\jni" -Force
          else
            mkdir -p node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/
          fi
        shell: pwsh

      - name: Copy dummy MMKV CMakeLists.txt (for CI build)
        run: node ./scripts/copy-mmkv-cmakelists.js

      - name: Debug- List MMKV codegen JNI dir
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            dir node_modules\\react-native-mmkv\\android\\build\\generated\\source\\codegen\\jni\\
          else
            ls -l node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/
          fi
        shell: pwsh

      - name: Debug- Show dummy MMKV CMakeLists.txt
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            type node_modules\\react-native-mmkv\\android\\build\\generated\\source\\codegen\\jni\\CMakeLists.txt
          else
            cat node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/CMakeLists.txt
          fi
        shell: pwsh

      - name: Gradle preBuild (generate autolinking files)
        run: |
          cd android
          ./gradlew :app:preBuild
          cd ..
        shell: bash

      - name: Patch autolinking.cmake to remove MMKV JNI C++ build
        run: node ./scripts/patch-autolinking-cmake.js

      - name: Patch autolinking.cpp to remove MMKV JNI includes
        run: node ./scripts/patch-autolinking-cpp.js

      - name: Debug- Show patched autolinking.cpp
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            type android\\app\\build\\generated\\autolinking\\src\\main\\jni\\autolinking.cpp
          else
            cat android/app/build/generated/autolinking/src/main/jni/autolinking.cpp
          fi
        shell: pwsh

      - name: Build release APK
        run: ./gradlew assembleRelease
        working-directory: android
        shell: bash

      - name: Set APK version suffix
        id: apk_version
        run: |
          if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "suffix=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "suffix=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Rename APK with version
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            Rename-Item -Path android\\app\\build\\outputs\\apk\\release\\app-release.apk -NewName app-release-${{ steps.apk_version.outputs.suffix }}.apk
          else
            mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk
          fi
        shell: pwsh

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-${{ steps.apk_version.outputs.suffix }}
          path: |
            android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk
          # retention-days: 3
