name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./android/gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Assemble APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
      - name: Debug- Show dummy MMKV CMakeLists.txt
        run: "cat node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/CMakeLists.txt"

      - name: Gradle preBuild (generate autolinking files)
        run: |
          cd android
          ./gradlew :app:preBuild
          cd ..

      - name: Patch autolinking.cmake to remove MMKV JNI C++ build
        run: node ./scripts/patch-autolinking-cmake.js

      - name: Patch autolinking.cpp to remove MMKV JNI includes
        run: node ./scripts/patch-autolinking-cpp.js

      - name: Debug- Show patched autolinking.cpp
        run: cat android/app/build/generated/autolinking/src/main/jni/autolinking.cpp

      - name: Build release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Set APK version suffix
        id: apk_version
        run: |
          if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "suffix=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "suffix=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Rename APK with version
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-${{ steps.apk_version.outputs.suffix }}
          path: android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk
