name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Clean Android build folders
        run: rm -rf android/app/build android/build

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Workaround for react-native-mmkv codegen on CI
        run: mkdir -p node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/

      - name: Copy dummy MMKV CMakeLists.txt (for CI build)
        run: node ./scripts/copy-mmkv-cmakelists.js

      - name: Debug- List MMKV codegen JNI dir
        run: "ls -l node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/"

      - name: Debug- Show dummy MMKV CMakeLists.txt
        run: "cat node_modules/react-native-mmkv/android/build/generated/source/codegen/jni/CMakeLists.txt"

      - name: Gradle preBuild (generate autolinking files)
        run: |
          cd android
          ./gradlew :app:preBuild
          cd ..

      - name: Patch autolinking.cmake to remove MMKV JNI C++ build
        run: node ./scripts/patch-autolinking-cmake.js

      - name: Patch autolinking.cpp to remove MMKV JNI includes
        run: node ./scripts/patch-autolinking-cpp.js

      - name: Debug- Show patched autolinking.cpp
        run: cat android/app/build/generated/autolinking/src/main/jni/autolinking.cpp

      - name: Build release APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Set APK version suffix
        id: apk_version
        run: |
          if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "suffix=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "suffix=${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi

      - name: Rename APK with version
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk-${{ steps.apk_version.outputs.suffix }}
          path: android/app/build/outputs/apk/release/app-release-${{ steps.apk_version.outputs.suffix }}.apk
